(()=>{'use strict';
const bridge=window.__notionBridge;
const daily=document.getElementById('daily');
if(!bridge||!daily||window.__weeklyPlannerStarted)return;
window.__weeklyPlannerStarted=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const dateObj=s=>new Date(String(s)+'T12:00:00');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const addDays=(s,n)=>{const d=dateObj(s);d.setDate(d.getDate()+n);return iso(d)};
const fiveDays=anchor=>Array.from({length:5},(_,i)=>addDays(anchor,i));
const todayIso=()=>iso(new Date());
const todayAnchor=()=>addDays(todayIso(),-3);
const weekdayOf=date=>'日一二三四五六'[dateObj(date).getDay()];
const taskSpan=t=>{const p=String(t.time||'').split('—');return {start:p[0]||'09:00',end:p[1]||'09:30'}};
const toMinutes=s=>{const m=String(s||'').match(/^(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):540};
const START_HOUR=6,END_HOUR=24,HOUR_PX=64,DAY_MINUTES=(END_HOUR-START_HOUR)*60;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let anchor=todayAnchor(),historyTarget=todayIso();
const style=document.createElement('style');
style.textContent=`
.week-planner{margin:0 0 18px;border:1px solid #e3e5eb;border-radius:18px;background:#fff;box-shadow:0 10px 30px rgba(29,43,72,.05);overflow:hidden}.week-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap;padding:18px 18px 14px;border-bottom:1px solid #eceef2}.week-head h3{margin:0;font-size:17px;color:#20242c}.week-head p{margin:5px 0 0;font-size:10px;color:#858b96;line-height:1.6}.week-actions{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.week-btn{border:1px solid #dedfe5;background:#fff;color:#555d69;border-radius:8px;padding:7px 10px;font-size:9px;font-weight:800;cursor:pointer}.week-btn:hover{background:#f7f7f8}.week-btn.primary{background:#202124;border-color:#202124;color:#fff}.week-range{font-size:10px;font-weight:800;color:#555d69;padding:7px 9px;background:#f4f4f5;border-radius:8px}
.ncal-wrap{overflow:auto;max-height:760px;background:#fff}.ncal{min-width:930px;display:grid;grid-template-columns:58px repeat(5,minmax(166px,1fr));position:relative}.ncal-corner{position:sticky;top:0;left:0;z-index:7;background:#fff;border-right:1px solid #eceef2;border-bottom:1px solid #eceef2;height:58px}.ncal-day-head{position:sticky;top:0;z-index:6;height:58px;background:rgba(255,255,255,.96);backdrop-filter:blur(10px);border-right:1px solid #eceef2;border-bottom:1px solid #eceef2;padding:8px 9px;display:flex;align-items:center;justify-content:space-between;gap:6px}.ncal-day-head.today{background:#f5f4ff}.ncal-day-name{display:flex;align-items:center;gap:7px;min-width:0}.ncal-date-dot{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;font-size:11px;font-weight:900;color:#30343b;background:#f3f3f4;flex:0 0 auto}.ncal-day-head.today .ncal-date-dot{background:#6d62d6;color:#fff}.ncal-day-text{min-width:0}.ncal-day-text strong{display:block;font-size:10px;color:#333841;white-space:nowrap}.ncal-day-text small{display:block;font-size:8px;color:#989da6;margin-top:2px}.ncal-head-tools{display:flex;gap:3px}.ncal-icon{border:0;background:transparent;color:#858a94;border-radius:6px;padding:4px 5px;font-size:8px;font-weight:800;cursor:pointer}.ncal-icon:hover{background:#eeeef1;color:#454b55}
.ncal-times{position:sticky;left:0;z-index:4;background:#fff;border-right:1px solid #eceef2;height:${(END_HOUR-START_HOUR)*HOUR_PX}px}.ncal-time{position:absolute;right:8px;transform:translateY(-7px);font-size:8px;color:#9ba0aa}.ncal-day{position:relative;height:${(END_HOUR-START_HOUR)*HOUR_PX}px;border-right:1px solid #eceef2;background-image:repeating-linear-gradient(to bottom,transparent 0,transparent ${HOUR_PX-1}px,#eceef2 ${HOUR_PX-1}px,#eceef2 ${HOUR_PX}px)}.ncal-day.today{background-color:#fcfbff}.ncal-half{position:absolute;left:0;right:0;border-top:1px solid #f4f4f6;pointer-events:none}.ncal-event{position:absolute;left:5px;right:5px;border-radius:7px;background:#eeeafd;border:1px solid #d9d2fb;padding:5px 23px 5px 7px;overflow:hidden;cursor:pointer;box-shadow:0 1px 2px rgba(30,32,38,.04);transition:transform .12s,box-shadow .12s;min-height:26px}.ncal-event:hover{transform:translateY(-1px);box-shadow:0 5px 14px rgba(48,43,91,.11);z-index:3}.ncal-event.done{background:#f0f1f3;border-color:#e0e2e5;opacity:.72}.ncal-event.phd{background:#e9f6f1;border-color:#cfe9df}.ncal-event.apply{background:#fff2e7;border-color:#f6dcc6}.ncal-event-title{font-size:9px;font-weight:850;color:#373b43;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ncal-event-time{font-size:7px;color:#717783;margin-top:2px}.ncal-copy{position:absolute;right:4px;top:4px;border:0;background:rgba(255,255,255,.68);border-radius:5px;width:18px;height:18px;font-size:9px;cursor:pointer;color:#656b75}.ncal-copy:hover{background:#fff;color:#4e45b6}.ncal-now{position:absolute;left:0;right:0;height:1px;background:#e04f5f;z-index:5;pointer-events:none}.ncal-now:before{content:'';position:absolute;left:-4px;top:-3px;width:7px;height:7px;border-radius:50%;background:#e04f5f}.ncal-empty-note{position:absolute;top:14px;left:10px;right:10px;font-size:8px;color:#adb1b9;text-align:center}
.week-history{padding:14px 18px 17px;border-top:1px solid #eceef2}.week-history-head{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.week-history-head strong{font-size:11px}.week-history-head span{font-size:8px;color:#9298a3}.week-history-target{border:1px solid #dde0e6;border-radius:7px;background:#fff;padding:6px 7px;font-size:9px}.week-history-list{display:flex;gap:7px;overflow-x:auto;padding:9px 1px 2px}.week-history-item{flex:0 0 195px;border:1px solid #e8e9ed;border-radius:9px;padding:8px;background:#fafafa}.week-history-item b{display:block;font-size:9px;color:#3d424a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.week-history-item small{display:block;font-size:7px;color:#969ca6;margin:3px 0 6px}.week-mini{border:1px solid #e0e2e7;background:#fff;color:#626975;border-radius:6px;padding:5px 6px;font-size:8px;font-weight:800;cursor:pointer}.week-mini:hover{background:#f3f2ff;color:#5f54c4}.week-toast{font-size:8px;color:#2d7963;margin-top:8px;min-height:12px}
@media(max-width:730px){.week-head{padding:14px}.week-actions{width:100%}.week-actions .week-btn{flex:1}.ncal{min-width:850px}.week-history{padding:12px 14px}.ncal-wrap{max-height:660px}}
`;
document.head.appendChild(style);
const box=document.createElement('div');box.className='week-planner';
const grid=daily.querySelector('.daily-grid');(grid||daily.firstChild).parentNode.insertBefore(box,grid||daily.firstChild);
function notify(msg){const el=box.querySelector('.week-toast');if(el)el.textContent=msg}
function setMainDate(date){const input=document.getElementById('date');if(input){input.value=date;input.dispatchEvent(new Event('change',{bubbles:true}))}}
function cloneTaskTo(source,target){const sp=taskSpan(source);bridge.upsert(target,'','',{title:source.title,description:source.description||'',cat:source.cat||'civil',start:sp.start,end:sp.end,done:false})}
function copyWholeDay(sourceDate,targetDate){const src=bridge.snapshot(sourceDate),target=bridge.snapshot(targetDate);if(!src.tasks.length){notify(`${sourceDate} 没有任务可复制。`);return}if(!confirm(`把 ${sourceDate} 的 ${src.tasks.length} 项任务整套复制到 ${targetDate}？\n\n会替换目标日期当前任务，但不会复制完成状态。`))return;for(const t of target.tasks)bridge.remove(targetDate,t.id,target.mode||'');for(const t of src.tasks)cloneTaskTo(t,targetDate);bridge.commit();historyTarget=targetDate;render();notify(`已把 ${sourceDate} 的整套任务复制到 ${targetDate}。`)}
function copyOne(sourceDate,id,targetDate){const src=bridge.snapshot(sourceDate),task=src.tasks.find(x=>String(x.id)===String(id));if(!task)return;cloneTaskTo(task,targetDate);bridge.commit();historyTarget=targetDate;render();notify(`已复制「${task.title}」到 ${targetDate}。`)}
function recentTasks(){const seen=new Set(),out=[];for(let i=1;i<=21;i++){const date=addDays(todayIso(),-i),snap=bridge.snapshot(date);for(const t of snap.tasks){const key=[t.title,t.cat,t.time].join('|');if(seen.has(key))continue;seen.add(key);out.push({date,...t});if(out.length>=24)return out}}return out}
function eventStyle(task){const sp=taskSpan(task),start=clamp(toMinutes(sp.start),START_HOUR*60,END_HOUR*60),rawEnd=toMinutes(sp.end),end=rawEnd<=start?Math.min(start+60,END_HOUR*60):clamp(rawEnd,START_HOUR*60,END_HOUR*60),top=((start-START_HOUR*60)/60)*HOUR_PX,height=Math.max(26,((end-start)/60)*HOUR_PX-2);return `top:${top}px;height:${height}px`}
function renderDay(date,today){const snap=bridge.snapshot(date),tasks=snap.tasks||[],now=new Date(),nowLine=date===today&&now.getHours()>=START_HOUR&&now.getHours()<END_HOUR?`<div class="ncal-now" style="top:${((now.getHours()*60+now.getMinutes()-START_HOUR*60)/60)*HOUR_PX}px"></div>`:'';return `<div class="ncal-day ${date===today?'today':''}" data-cal-day="${date}">${Array.from({length:(END_HOUR-START_HOUR)*2-1},(_,i)=>i%2===0?`<div class="ncal-half" style="top:${(i+1)*HOUR_PX/2}px"></div>`:'').join('')}${!tasks.length?'<div class="ncal-empty-note">暂无安排</div>':''}${tasks.map(t=>{const sp=taskSpan(t),cat=t.cat==='phd'?'phd':t.cat==='apply'?'apply':'civil';return `<div class="ncal-event ${cat} ${t.done?'done':''}" style="${eventStyle(t)}" data-open-event="${esc(date)}" title="${esc(t.title)} · ${esc(t.time)}"><div class="ncal-event-title">${t.done?'✓ ':''}${esc(t.title)}</div><div class="ncal-event-time">${esc(sp.start)} — ${esc(sp.end)}</div><button class="ncal-copy" data-copy-task="${esc(t.id)}" data-source-date="${date}" data-target-date="${addDays(date,1)}" title="复制到下一天">＋</button></div>`}).join('')}${nowLine}</div>`}
function render(){
 const days=fiveDays(anchor),today=todayIso(),recent=recentTasks();if(!days.includes(historyTarget))historyTarget=days.includes(bridge.selected())?bridge.selected():today;
 const heads=days.map((date,idx)=>{const count=(bridge.snapshot(date).tasks||[]).length;return `<div class="ncal-day-head ${date===today?'today':''}"><div class="ncal-day-name"><div class="ncal-date-dot">${date.slice(-2)}</div><div class="ncal-day-text"><strong>${date===today?'今天 · ':''}周${weekdayOf(date)}</strong><small>${date.slice(5)} · ${count} 项</small></div></div><div class="ncal-head-tools"><button class="ncal-icon" data-open-day="${date}">打开</button>${idx>0?`<button class="ncal-icon" data-copy-day="${date}" data-source-day="${days[idx-1]}">复制前一天</button>`:''}</div></div>`}).join('');
 const times=`<div class="ncal-times">${Array.from({length:END_HOUR-START_HOUR},(_,i)=>`<div class="ncal-time" style="top:${i*HOUR_PX}px">${pad(START_HOUR+i)}:00</div>`).join('')}</div>`;
 box.innerHTML=`<div class="week-head"><div><h3>五日日历</h3><p>Notion Calendar 风格时间轴 · 今天固定在倒数第二列，前 3 天 + 今天 + 明天。</p></div><div class="week-actions"><button class="week-btn" data-window-prev>‹ 前 1 天</button><span class="week-range">${days[0]} — ${days[4]}</span><button class="week-btn" data-window-next>后 1 天 ›</button><button class="week-btn primary" data-window-today>回到今天</button></div></div><div class="ncal-wrap" data-cal-scroll><div class="ncal"><div class="ncal-corner"></div>${heads}${times}${days.map(d=>renderDay(d,today)).join('')}</div></div><div class="week-history"><div class="week-history-head"><div><strong>最近历史任务 · 点一下直接复制</strong><span>最近 21 天去重</span></div><label style="font-size:8px;color:#7e899c">复制到 <select class="week-history-target" data-history-target>${days.map(d=>`<option value="${d}" ${d===historyTarget?'selected':''}>${d.slice(5)} · 周${weekdayOf(d)}</option>`).join('')}</select></label></div><div class="week-history-list">${recent.length?recent.map(t=>`<div class="week-history-item"><b title="${esc(t.title)}">${esc(t.title)}</b><small>${esc(t.date)} · ${esc(t.time)}</small><button class="week-mini" data-history-copy="${esc(t.id)}" data-history-date="${esc(t.date)}">＋ 复制到 ${historyTarget.slice(5)}</button></div>`).join(''):'<div style="font-size:9px;color:#999;padding:8px">最近 21 天还没有可复用任务。</div>'}</div><div class="week-toast" aria-live="polite"></div></div>`;
 const scroller=box.querySelector('[data-cal-scroll]');if(scroller&&!scroller.dataset.scrolled){const now=new Date(),targetHour=clamp(now.getHours()-2,START_HOUR,END_HOUR-6);scroller.scrollTop=(targetHour-START_HOUR)*HOUR_PX;scroller.dataset.scrolled='1'}
}
box.addEventListener('click',e=>{
 const prev=e.target.closest('[data-window-prev]'),next=e.target.closest('[data-window-next]'),current=e.target.closest('[data-window-today]'),open=e.target.closest('[data-open-day]'),event=e.target.closest('[data-open-event]'),copyDay=e.target.closest('[data-copy-day]'),copyTask=e.target.closest('[data-copy-task]'),historyCopy=e.target.closest('[data-history-copy]');
 if(copyTask){e.stopPropagation();copyOne(copyTask.dataset.sourceDate,copyTask.dataset.copyTask,copyTask.dataset.targetDate);return}if(prev){anchor=addDays(anchor,-1);render();return}if(next){anchor=addDays(anchor,1);render();return}if(current){anchor=todayAnchor();historyTarget=todayIso();render();return}if(open){setMainDate(open.dataset.openDay);historyTarget=open.dataset.openDay;render();document.getElementById('dragCalendar')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(event){setMainDate(event.dataset.openEvent);historyTarget=event.dataset.openEvent;document.getElementById('dragCalendar')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(copyDay){copyWholeDay(copyDay.dataset.sourceDay,copyDay.dataset.copyDay);return}if(historyCopy){copyOne(historyCopy.dataset.historyDate,historyCopy.dataset.historyCopy,historyTarget);return}
});
box.addEventListener('change',e=>{const target=e.target.closest('[data-history-target]');if(target){historyTarget=target.value;render()}});
const dateInput=document.getElementById('date');dateInput?.addEventListener('change',()=>{historyTarget=dateInput.value||bridge.selected();render()});
const oldCloudChanged=window.__dualCloudChanged;window.__dualCloudChanged=(...args)=>{try{oldCloudChanged?.(...args)}finally{clearTimeout(window.__weeklyRefreshTimer);window.__weeklyRefreshTimer=setTimeout(render,80)}};
const oldCommit=bridge.commit;bridge.commit=()=>{const r=oldCommit();setTimeout(render,0);return r};
let lastToday=todayIso();setInterval(()=>{const now=todayIso();if(now!==lastToday){lastToday=now;anchor=todayAnchor();historyTarget=now}render()},60000);
render();
})();