(()=>{'use strict';
const bridge=window.__notionBridge;
const daily=document.getElementById('daily');
if(!bridge||!daily||window.__weeklyPlannerStarted)return;
window.__weeklyPlannerStarted=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const dateObj=s=>new Date(String(s)+'T12:00:00');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const addDays=(s,n)=>{const d=dateObj(s);d.setDate(d.getDate()+n);return iso(d)};
const weekStart=s=>{const d=dateObj(s),wd=d.getDay();d.setDate(d.getDate()-(wd===0?6:wd-1));return iso(d)};
const weekDays=s=>Array.from({length:7},(_,i)=>addDays(s,i));
const taskSpan=t=>{const p=String(t.time||'').split('—');return {start:p[0]||'09:00',end:p[1]||'09:30'}};
let anchor=weekStart(bridge.selected()),historyTarget=bridge.selected();
const style=document.createElement('style');
style.textContent=`
.week-planner{margin:0 0 18px;border:1px solid #e2e6f0;border-radius:20px;background:#fff;box-shadow:0 10px 30px rgba(29,43,72,.055);padding:20px;overflow:hidden}
.week-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap;margin-bottom:15px}.week-head h3{margin:0;font-size:17px;color:#26364e}.week-head p{margin:6px 0 0;font-size:11px;color:#7f8ba0;line-height:1.7}.week-actions{display:flex;gap:7px;flex-wrap:wrap}.week-btn{border:1px solid #dfe4ee;background:#fff;color:#526178;border-radius:9px;padding:8px 10px;font-size:10px;font-weight:800;cursor:pointer}.week-btn:hover{background:#f7f7ff;border-color:#c9c5f5}.week-btn.primary{background:#6d62d6;border-color:#6d62d6;color:#fff}.week-range{font-size:11px;font-weight:850;color:#6259c4;padding:8px 10px;background:#f3f1ff;border-radius:999px}
.week-grid{display:grid;grid-template-columns:repeat(7,minmax(190px,1fr));gap:10px;overflow-x:auto;padding-bottom:5px}.week-day{border:1px solid #e7eaf1;border-radius:14px;background:linear-gradient(180deg,#fff,#fbfcff);padding:11px;min-width:190px}.week-day.today{border-color:#bcb6f2;box-shadow:0 0 0 2px rgba(112,102,223,.07)}.week-day-head{display:flex;justify-content:space-between;gap:7px;align-items:flex-start;margin-bottom:9px}.week-day-head strong{font-size:12px;color:#2e3c53}.week-day-head small{display:block;margin-top:3px;font-size:9px;color:#929bac}.week-day-tools{display:flex;gap:4px;flex-wrap:wrap}.week-mini{border:1px solid #e0e4ed;background:#fff;color:#637088;border-radius:7px;padding:5px 6px;font-size:8px;font-weight:800;cursor:pointer}.week-mini:hover{background:#f4f3ff;color:#5f54c4}.week-task{border-top:1px solid #eef0f5;padding:8px 0}.week-task:first-of-type{border-top:0}.week-task-title{font-size:10px;font-weight:800;color:#37455b;line-height:1.45;overflow-wrap:anywhere}.week-task-meta{font-size:8px;color:#8a95a7;margin-top:3px}.week-time-edit{display:grid;grid-template-columns:1fr 1fr auto;gap:4px;margin-top:6px}.week-time-edit input{width:100%;min-width:0;border:1px solid #e0e4ee;border-radius:7px;padding:5px 4px;font-size:9px;color:#334057;background:#fff}.week-empty{font-size:10px;color:#9aa3b1;padding:14px 4px;line-height:1.6}.week-copy-next{margin-top:5px;border:0;background:transparent;color:#655bc7;font-size:8px;font-weight:800;padding:0;cursor:pointer}.week-copy-next:hover{text-decoration:underline}
.week-history{margin-top:16px;border-top:1px solid #eceef4;padding-top:14px}.week-history-head{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.week-history-head strong{font-size:12px}.week-history-head span{font-size:9px;color:#8c96a7}.week-history-target{border:1px solid #dde2ec;border-radius:8px;background:#fff;padding:7px 8px;font-size:10px}.week-history-list{display:flex;gap:7px;overflow-x:auto;padding:10px 1px 3px}.week-history-item{flex:0 0 210px;border:1px solid #e7e9f1;border-radius:11px;padding:9px;background:#fcfcff}.week-history-item b{display:block;font-size:10px;color:#37455b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.week-history-item small{display:block;font-size:8px;color:#929cad;margin:4px 0 7px}.week-toast{font-size:9px;color:#2d7963;margin-top:9px;min-height:14px}
@media(max-width:730px){.week-planner{padding:13px}.week-grid{grid-template-columns:repeat(7,minmax(175px,1fr))}.week-head{align-items:flex-start}.week-actions{width:100%}.week-actions .week-btn{flex:1}.week-history-item{flex-basis:190px}}
`;
document.head.appendChild(style);
const box=document.createElement('div');
box.className='week-planner';
const grid=daily.querySelector('.daily-grid');
(grid||daily.firstChild).parentNode.insertBefore(box,grid||daily.firstChild);
function notify(msg){const el=box.querySelector('.week-toast');if(el)el.textContent=msg}
function setMainDate(date){const input=document.getElementById('date');if(input){input.value=date;input.dispatchEvent(new Event('change',{bubbles:true}))}}
function cloneTaskTo(source,target){const sp=taskSpan(source);bridge.upsert(target,'','',{title:source.title,description:source.description||'',cat:source.cat||'civil',start:sp.start,end:sp.end,done:false});}
function copyWholeDay(sourceDate,targetDate){const src=bridge.snapshot(sourceDate),target=bridge.snapshot(targetDate);if(!src.tasks.length){notify(`${sourceDate} 没有任务可复制。`);return}if(!confirm(`把 ${sourceDate} 的 ${src.tasks.length} 项任务整套复制到 ${targetDate}？\n\n会替换目标日期当前任务，但不会复制完成状态。`))return;for(const t of target.tasks)bridge.remove(targetDate,t.id,target.mode||'');for(const t of src.tasks)cloneTaskTo(t,targetDate);bridge.commit();historyTarget=targetDate;render();notify(`已把 ${sourceDate} 的整套任务复制到 ${targetDate}。`)}
function copyOne(sourceDate,id,targetDate){const src=bridge.snapshot(sourceDate),task=src.tasks.find(x=>String(x.id)===String(id));if(!task)return;cloneTaskTo(task,targetDate);bridge.commit();historyTarget=targetDate;render();notify(`已复制「${task.title}」到 ${targetDate}。`)}
function updateTime(date,id,start,end){const snap=bridge.snapshot(date),task=snap.tasks.find(x=>String(x.id)===String(id));if(!task||!start||!end||start===end){notify('开始时间和结束时间不能相同。');return}bridge.upsert(date,id,snap.mode||'',{title:task.title,description:task.description||'',cat:task.cat||'civil',start,end,done:!!task.done});bridge.commit();render();notify(`已更新 ${date} 的「${task.title}」。`)}
function recentTasks(){const seen=new Set(),out=[];for(let i=1;i<=21;i++){const date=addDays(anchor,-i),snap=bridge.snapshot(date);for(const t of snap.tasks){const key=[t.title,t.cat,t.time].join('|');if(seen.has(key))continue;seen.add(key);out.push({date,...t});if(out.length>=24)return out}}return out}
function render(){
 const days=weekDays(anchor),today=iso(new Date()),recent=recentTasks();if(!days.includes(historyTarget))historyTarget=days.includes(bridge.selected())?bridge.selected():days[0];
 box.innerHTML=`<div class="week-head"><div><h3>一周日程 · 直接排 7 天</h3><p>一周任务同时展开。每项任务可直接改起止时间；也可以复制前一天整套安排，或把最近做过的单项任务复制到任意一天。</p></div><div class="week-actions"><button class="week-btn" data-week-prev>‹ 上一周</button><span class="week-range">${days[0]} — ${days[6]}</span><button class="week-btn" data-week-next>下一周 ›</button><button class="week-btn primary" data-week-current>回到本周</button></div></div><div class="week-grid">${days.map((date,idx)=>{const snap=bridge.snapshot(date),wd='一二三四五六日'[idx],tasks=snap.tasks;return `<div class="week-day ${date===today?'today':''}" data-week-day="${date}"><div class="week-day-head"><div><strong>周${wd} · ${date.slice(5)}</strong><small>${tasks.length} 项任务</small></div><div class="week-day-tools"><button class="week-mini" data-open-day="${date}">打开</button>${idx>0?`<button class="week-mini" data-copy-day="${date}" data-source-day="${days[idx-1]}">复制前一天</button>`:''}</div></div>${tasks.length?tasks.map(t=>{const sp=taskSpan(t);return `<div class="week-task"><div class="week-task-title">${esc(t.title)}</div><div class="week-task-meta">${esc(t.cat==='phd'?'考博 · 三高':t.cat==='apply'?'论文 / 申请':'考公')} · ${esc(t.time)}</div><div class="week-time-edit"><input type="time" value="${esc(sp.start)}" data-week-start><input type="time" value="${esc(sp.end)}" data-week-end><button class="week-mini" data-week-save-time="${esc(t.id)}" data-date="${date}">保存</button></div><button class="week-copy-next" data-copy-task="${esc(t.id)}" data-source-date="${date}" data-target-date="${idx<6?days[idx+1]:addDays(date,1)}">复制到下一天 →</button></div>`}).join(''):'<div class="week-empty">当天暂无任务。可从下方历史任务直接复制进来。</div>'}</div>`}).join('')}</div><div class="week-history"><div class="week-history-head"><div><strong>最近历史任务 · 点一下直接复制</strong><span>去重展示最近 21 天做过的任务</span></div><label style="font-size:9px;color:#7e899c">复制到 <select class="week-history-target" data-history-target>${days.map(d=>`<option value="${d}" ${d===historyTarget?'selected':''}>${d.slice(5)} · 周${'一二三四五六日'[days.indexOf(d)]}</option>`).join('')}</select></label></div><div class="week-history-list">${recent.length?recent.map(t=>`<div class="week-history-item"><b title="${esc(t.title)}">${esc(t.title)}</b><small>${esc(t.date)} · ${esc(t.time)}</small><button class="week-mini" data-history-copy="${esc(t.id)}" data-history-date="${esc(t.date)}">＋ 复制到 ${historyTarget.slice(5)}</button></div>`).join(''):'<div class="week-empty">最近 21 天还没有可复用的历史任务。</div>'}</div><div class="week-toast" aria-live="polite"></div></div>`;
}
box.addEventListener('click',e=>{
 const prev=e.target.closest('[data-week-prev]'),next=e.target.closest('[data-week-next]'),current=e.target.closest('[data-week-current]'),open=e.target.closest('[data-open-day]'),copyDay=e.target.closest('[data-copy-day]'),copyTask=e.target.closest('[data-copy-task]'),saveTime=e.target.closest('[data-week-save-time]'),historyCopy=e.target.closest('[data-history-copy]');
 if(prev){anchor=addDays(anchor,-7);render();return}if(next){anchor=addDays(anchor,7);render();return}if(current){anchor=weekStart(bridge.selected());render();return}if(open){setMainDate(open.dataset.openDay);historyTarget=open.dataset.openDay;render();document.getElementById('dragCalendar')?.scrollIntoView({behavior:'smooth',block:'start'});return}if(copyDay){copyWholeDay(copyDay.dataset.sourceDay,copyDay.dataset.copyDay);return}if(copyTask){copyOne(copyTask.dataset.sourceDate,copyTask.dataset.copyTask,copyTask.dataset.targetDate);return}if(saveTime){const row=saveTime.closest('.week-time-edit');updateTime(saveTime.dataset.date,saveTime.dataset.weekSaveTime,row?.querySelector('[data-week-start]')?.value,row?.querySelector('[data-week-end]')?.value);return}if(historyCopy){copyOne(historyCopy.dataset.historyDate,historyCopy.dataset.historyCopy,historyTarget);return}
});
box.addEventListener('change',e=>{const target=e.target.closest('[data-history-target]');if(target){historyTarget=target.value;render()}});
const dateInput=document.getElementById('date');dateInput?.addEventListener('change',()=>{historyTarget=dateInput.value||bridge.selected();anchor=weekStart(historyTarget);render()});
const oldCloudChanged=window.__dualCloudChanged;window.__dualCloudChanged=(...args)=>{try{oldCloudChanged?.(...args)}finally{clearTimeout(window.__weeklyRefreshTimer);window.__weeklyRefreshTimer=setTimeout(render,80)}};
const oldCommit=bridge.commit;bridge.commit=()=>{const r=oldCommit();setTimeout(render,0);return r};
render();
})();
